const OFFICIAL='https://ellibrary.moe.gov.eg/EgyptianBaccalaureate/';
const BOOKS='https://egyptianbaccalaureate.blob.core.windows.net/egyptianbaccalaureate/';
const ASSESS=BOOKS+'EB-Assessments/';
const DATA={
 paths:[
  {id:'life',name:'الطب وعلوم الحياة',icon:'✚',desc:'مسار يهتم بالعلوم الطبيعية والحياة',subjects:['الرياضيات','الفيزياء']},
  {id:'eng',name:'الهندسة وعلوم الحاسب',icon:'⌘',desc:'مسار يجمع العلوم والحساب والبرمجة والذكاء الاصطناعي',subjects:['الكيمياء','البرمجة والذكاء الاصطناعي']},
  {id:'biz',name:'الأعمال',icon:'▦',desc:'مسار يركز على المحاسبة وإدارة الأعمال',subjects:['المحاسبة','إدارة الأعمال']},
  {id:'arts',name:'الآداب والفنون',icon:'✦',desc:'مسار يضم علم النفس واللغة الأجنبية الثانية',subjects:['علم النفس','اللغة الأجنبية الثانية']}
 ],
 core:[
  {name:'اللغة العربية',url:'https://studentbooks.moe.gov.eg/EgyptianBaccalaureate/CoreSubjects/Arabic/'},
  {name:'اللغة الأجنبية الأولى',url:'https://studentbooks.moe.gov.eg/EgyptianBaccalaureate/CoreSubjects/FirstForeignLanguage/'},
  {name:'التاريخ المصري',url:'https://studentbooks.moe.gov.eg/EgyptianBaccalaureate/CoreSubjects/EgyptianHistory/'}
 ],
 books:{
  'الرياضيات':{url:BOOKS+'Mathematics-Ar-EB-Part1.pdf',p2:BOOKS+'Mathematics-Ar-EB-Part2.pdf',assessment:ASSESS+'Mathematics-Ar-EB-Assessments-1.pdf'},
  'الفيزياء':{url:BOOKS+'Physics-Ar-EB-part1.pdf',p2:BOOKS+'Physics-Ar-EB-part2.pdf',assessment:ASSESS+'Physics-Ar-EB-Assessments-1.pdf'},
  'الكيمياء':{url:BOOKS+'Chemistry-Ar-EB-part1.pdf',p2:BOOKS+'Chemistry-Ar-EB-part2.pdf',assessment:ASSESS+'Chemistry-Ar-EB-Assessments-1.pdf'},
  'البرمجة والذكاء الاصطناعي':{url:BOOKS+'Programming-ArtificialIntelligence-Ar-EB-part1.pdf',p2:BOOKS+'Programming-ArtificialIntelligence-Ar-EB-part2.pdf',assessment:ASSESS+'Programming-ArtificialIntelligence-Ar-EB-Assessments-1.pdf'},
  'المحاسبة':{url:BOOKS+'Accuonting-Ar-EB-Part1.pdf',p2:BOOKS+'Accuonting-Ar-EB-Part2.pdf',assessment:ASSESS+'Accuonting-Ar-EB-Assessments-1.pdf'},
  'إدارة الأعمال':{url:BOOKS+'Business-AR-EB-Part1.pdf',p2:BOOKS+'Business-AR-EB-Part2.pdf',assessment:ASSESS+'Business-AR-EB-Assessments-1.pdf'},
  'علم النفس':{url:BOOKS+'Psychology-EB-part1.pdf',p2:BOOKS+'Psychology-EB-part2.pdf',assessment:ASSESS+'Psychology-EB-Assessments-1.pdf'},
  'اللغة الأجنبية الثانية':{url:'https://studentbooks.moe.gov.eg/EgyptianBaccalaureate/SpecializedSubjects/Arts-Humanities/SecondForeignLanguages/french/',extra:['الألمانية','الإسبانية','الإيطالية','الصينية']}
 },
 demoLessons:{
  'الرياضيات':['الدرس 1 — مدخل للمفهوم الرياضي','الدرس 2 — التمثيل والتحليل','تطبيقات ومسائل تدريبية'],
  'الفيزياء':['الدرس 1 — الطاقة وتحولاتها','الدرس 2 — نمذجة الظواهر','تطبيقات ومسائل تدريبية'],
  'الكيمياء':['الدرس 1 — بنية المادة','الدرس 2 — التغيرات والتفاعلات','تطبيقات ومسائل تدريبية'],
  'البرمجة والذكاء الاصطناعي':['الدرس 1 — التفكير الحاسوبي','الدرس 2 — الخوارزميات والبيانات','مختبر برمجي تفاعلي'],
  'المحاسبة':['الدرس 1 — مفاهيم المحاسبة','الدرس 2 — قراءة البيانات المالية','تطبيقات تدريبية'],
  'إدارة الأعمال':['الدرس 1 — أساسيات الإدارة','الدرس 2 — اتخاذ القرار','دراسة حالة'],
  'علم النفس':['الدرس 1 — مدخل إلى علم النفس','الدرس 2 — السلوك والتعلم','نشاط تحليلي'],
  'اللغة الأجنبية الثانية':['الوحدة 1','الوحدة 2','تدريب لغوي']
 }
};
const DEFAULT={admin:{username:'admin',email:'admin@example.com',password:'Mbc@2026',name:'مدير المنصة'},students:[{id:'s1',name:'طالب تجريبي',username:'student',email:'student@example.com',password:'Student@123',path:'eng'}],progress:{},theme:'light'};
let state=load(), role='student', currentUser=null, page='home', selectedPath=null, selectedSubject=null;
function load(){try{return {...DEFAULT,...JSON.parse(localStorage.getItem('MBC_V2')||'{}')}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('MBC_V2',JSON.stringify(state))}
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function navItems(){return role==='admin'?[['home','لوحة الإدارة','▦'],['paths','المسارات','⌁'],['subjects','المواد والدروس','◈'],['library','المكتبة الرسمية','▤'],['students','الطلاب','♙'],['tests','الاختبارات','✓'],['stats','الإحصائيات','◒'],['settings','الإعدادات','⚙']]:[['home','رحلتي التعليمية','⌂'],['paths','اختيار المسار','⌁'],['library','المكتبة الرسمية','▤'],['tests','اختباراتي','✓'],['results','نتائجي وتقدمي','◒'],['guide','دليل الاستخدام','?']];}
function renderShell(){
 $('#profileCard').innerHTML=`<div class="name">${currentUser.name}</div><div class="meta">${role==='admin'?'إدارة المنصة':'طالب • '+(DATA.paths.find(p=>p.id===currentUser.path)?.name||'لم يحدد مسارًا')}</div>`;
 const n=navItems().map(([id,label,ico])=>`<button class="${page===id?'active':''}" data-page="${id}"><b>${ico}</b> ${label}</button>`).join('');
 $('#navStudent').innerHTML=role==='student'?n:'';$('#navAdmin').innerHTML=role==='admin'?n:'';
 $$('.nav button').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
 $('#avatar').textContent=(currentUser.name||'م')[0];
}
function render(){renderShell();const titles={home:role==='admin'?'لوحة الإدارة':'رحلتي التعليمية',paths:'المسارات',library:'المكتبة الرسمية',tests:'الاختبارات',results:'النتائج والتقدم',guide:'دليل الاستخدام',subjects:'المواد والدروس',students:'الطلاب',stats:'الإحصائيات',settings:'الإعدادات'};$('#pageTitle').textContent=titles[page]||'موسوعة البكالوريا';$('#crumb').textContent='موسوعة البكالوريا';
 const c=$('#content'); if(page==='home')c.innerHTML=role==='admin'?adminHome():studentHome();else if(page==='paths')c.innerHTML=pathsPage();else if(page==='library')c.innerHTML=libraryPage();else if(page==='subjects')c.innerHTML=subjectsPage();else if(page==='students')c.innerHTML=studentsPage();else if(page==='tests')c.innerHTML=testsPage();else if(page==='stats')c.innerHTML=statsPage();else if(page==='settings')c.innerHTML=settingsPage();else if(page==='results')c.innerHTML=resultsPage();else c.innerHTML=guidePage();bindContent();}
function studentHome(){const path=DATA.paths.find(p=>p.id===currentUser.path);const prog=state.progress[currentUser.username]||{completed:2,percent:28};return `<div class="hero"><div><span class="eyebrow">رحلتك اليوم</span><h1>تعلم بفهم، مش بالحفظ فقط.</h1><p>ابدأ من خريطة المسار، افتح المادة، ذاكر من المصدر الرسمي، ثم جرّب النشاط التفاعلي واختبر نفسك.</p><div class="hero-actions"><button class="light-btn" data-action="path">ابدأ من خريطة المسار</button><button class="outline-light" data-action="library">افتح الكتب الرسمية</button></div></div><div class="journey"><div class="journey-line"></div><div class="journey-step done"><div class="journey-dot">✓</div><div><h4>اختيار المسار</h4><small>${path?path.name:'لم تختَر بعد'}</small></div></div><div class="journey-step done"><div class="journey-dot">✓</div><div><h4>استكشاف المحتوى</h4><small>المواد والكتب الرسمية</small></div></div><div class="journey-step"><div class="journey-dot">3</div><div><h4>التفاعل والتطبيق</h4><small>مختبرات وتحديات</small></div></div><div class="journey-step"><div class="journey-dot">4</div><div><h4>الاختبار والتحليل</h4><small>نتيجة + نقاط ضعف</small></div></div></div></div><div class="stats"><div class="stat"><div class="k">التقدم العام</div><div class="v">${prog.percent}%</div><div class="delta">استمر في الرحلة</div></div><div class="stat"><div class="k">أنشطة مكتملة</div><div class="v">${prog.completed}</div><div class="delta">نشاط تفاعلي</div></div><div class="stat"><div class="k">الاختبارات</div><div class="v">3</div><div class="delta">متاحة الآن</div></div><div class="stat"><div class="k">نقاط التعلم</div><div class="v">420</div><div class="delta">+60 هذا الأسبوع</div></div></div><div class="section-head"><div><h3>مواد مسارك</h3><p>افتح المادة للوصول للكتاب والفهرس والأنشطة.</p></div></div><div class="grid">${(path?.subjects||['اختر مسارك']).map(s=>subjectCard(s)).join('')}</div>`}
function subjectCard(s){return `<button class="card subject-card" data-subject="${esc(s)}"><div class="subject-icon">◈</div><div style="flex:1;text-align:right"><h4>${s}</h4><small>${(DATA.demoLessons[s]||[]).length} مراحل تعلم</small><div class="progress"><i style="width:${Math.floor(20+Math.random()*55)}%"></i></div></div><span>←</span></button>`}
function adminHome(){return `<div class="hero"><div><span class="eyebrow">مركز التحكم</span><h1>إدارة المنصة من مكان واحد.</h1><p>أنشئ المسارات والمواد والدروس والاختبارات، اربط الكتب الرسمية، وتابع تقدم الطلاب.</p><div class="hero-actions"><button class="light-btn" data-page="subjects">إدارة المحتوى</button><button class="outline-light" data-page="students">إدارة الطلاب</button></div></div><div class="journey"><div class="journey-step done"><div class="journey-dot">✓</div><div><h4>مصادر الوزارة</h4><small>روابط الكتب الرسمية</small></div></div><div class="journey-step done"><div class="journey-dot">✓</div><div><h4>محتوى تفاعلي</h4><small>دروس + أنشطة</small></div></div><div class="journey-step"><div class="journey-dot">3</div><div><h4>قياس التعلم</h4><small>اختبارات ونتائج</small></div></div></div></div><div class="stats"><div class="stat"><div class="k">الطلاب</div><div class="v">${state.students.length}</div><div class="delta">حسابات نشطة</div></div><div class="stat"><div class="k">المسارات</div><div class="v">4</div><div class="delta">بكالوريا الصف الثاني</div></div><div class="stat"><div class="k">مواد تخصصية</div><div class="v">8</div><div class="delta">مع المواد الأساسية</div></div><div class="stat"><div class="k">مصادر رسمية</div><div class="v">${DATA.core.length+8}</div><div class="delta">كتاب / تقييم</div></div></div><div class="section-head"><div><h3>الوصول السريع</h3><p>أهم أجزاء الإدارة.</p></div></div><div class="grid">${[['subjects','◈','المواد والدروس','إضافة وتحرير المحتوى'],['library','▤','المكتبة الرسمية','الكتب والتقييمات'],['tests','✓','الاختبارات','بنك الأسئلة والاختبارات'],['students','♙','الطلاب','حسابات الطلاب وإعادة التعيين']].map(x=>`<button class="card path-card" data-page="${x[0]}"><div class="path-icon">${x[1]}</div><div><h4>${x[2]}</h4><p>${x[3]}</p><div class="card-action">فتح القسم ←</div></div></button>`).join('')}</div>`}
function pathsPage(){return `<div class="section-head"><div><h3>مسارات البكالوريا</h3><p>المواد التالية مبنية على الهيكل المنشور للصف الثاني 2026/2027؛ والكتب الرسمية مرتبطة مباشرة بالمصادر الرسمية.</p></div></div><div class="grid">${DATA.paths.map(p=>`<button class="card path-card" data-path="${p.id}"><div class="path-icon">${p.icon}</div><div><h4>${p.name}</h4><p>${p.desc}</p><div class="card-action">${p.subjects.join(' • ')} ←</div></div></button>`).join('')}</div>`}
function libraryPage(){let rows=[...DATA.core.map(x=>({...x,type:'أساسية'})),...Object.entries(DATA.books).map(([name,b])=>({name,url:b.url,p2:b.p2,assessment:b.assessment,type:'تخصصية'}))];return `<div class="hero" style="margin-bottom:20px"><div><span class="eyebrow">مصدر رسمي</span><h1>المكتبة الإلكترونية</h1><p>الوصول إلى كتب الصف الثاني بكالوريا 2026/2027 من بوابة وزارة التربية والتعليم، مع روابط الكتب والتقييمات المتاحة.</p><div class="hero-actions"><button class="light-btn" data-url="${OFFICIAL}">فتح مكتبة الوزارة ↗</button></div></div><div class="card" style="background:#fff;color:#172033;align-self:stretch"><b>ملاحظة مهمة</b><p style="color:#697386;font-size:12px;line-height:1.8">المنصة لا تعيد نشر ملفات الكتب داخل الحزمة؛ بل تحفظ روابط المصدر الرسمي، ويمكن للإدارة ربط ملفات محلية لاحقًا عند توفرها.</p></div></div><div class="section-head"><div><h3>الكتب والفهارس</h3><p>الفهرس التفصيلي يظل مرتبطًا بالكتاب الرسمي نفسه، مع خريطة تعلم داخل المنصة.</p></div></div><div class="library-list">${rows.map(r=>`<div class="library-item"><div><b>${r.name}</b><small>${r.type} • المصدر: وزارة التربية والتعليم</small></div><div class="library-actions"><button class="small-btn fill" data-url="${r.url}">الكتاب / الصفحة ↗</button>${r.p2?`<button class="small-btn" data-url="${r.p2}">الجزء 2 ↗</button>`:''}${r.assessment?`<button class="small-btn" data-url="${r.assessment}">التقييمات ↗</button>`:''}</div></div>`).join('')}</div>`}
function subjectsPage(){return `<div class="filters"><input id="subjectSearch" placeholder="ابحث عن مادة..."><select id="pathFilter"><option value="all">كل المسارات</option>${DATA.paths.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')}</select></div><div id="subjectGrid" class="grid">${Object.keys(DATA.books).map(subjectCard).join('')}</div>`}
function studentsPage(){return `<div class="section-head"><div><h3>إدارة الطلاب</h3><p>إنشاء الحسابات وتحديد المسار وإعادة تعيين كلمة المرور.</p></div><button class="primary" data-action="addStudent">+ طالب جديد</button></div><table class="table"><thead><tr><th>الطالب</th><th>المستخدم</th><th>المسار</th><th>الحالة</th><th></th></tr></thead><tbody>${state.students.map(s=>`<tr><td>${s.name}</td><td>${s.username}</td><td>${DATA.paths.find(p=>p.id===s.path)?.name||'—'}</td><td>نشط</td><td><button class="small-btn" data-student="${s.id}">تعديل</button></td></tr>`).join('')}</tbody></table>`}
function testsPage(){return `<div class="section-head"><div><h3>مركز الاختبارات</h3><p>اختبارات قصيرة وتحديات واختبار شامل.</p></div>${role==='admin'?'<button class="primary" data-action="newTest">+ اختبار جديد</button>':''}</div><div class="grid">${[['تحدي سريع','10 أسئلة • 8 دقائق','يختبر الفهم السريع'],['اختبار مادة','20 سؤالًا • 25 دقيقة','أسئلة متنوعة وتغذية راجعة'],['محاكاة شاملة','40 سؤالًا • 50 دقيقة','تحليل النتيجة ونقاط الضعف']].map((x,i)=>`<button class="card path-card" data-test="${i}"><div class="path-icon">✓</div><div><h4>${x[0]}</h4><p>${x[1]}</p><div class="card-action">${x[2]} ←</div></div></button>`).join('')}</div>`}
function statsPage(){return `<div class="stats"><div class="stat"><div class="k">متوسط التقدم</div><div class="v">68%</div><div class="delta">آخر 30 يومًا</div></div><div class="stat"><div class="k">اختبارات منجزة</div><div class="v">124</div><div class="delta">+18 هذا الأسبوع</div></div><div class="stat"><div class="k">متوسط النتائج</div><div class="v">78%</div><div class="delta">تحسن 6%</div></div></div><div class="card"><h3>توزيع التقدم</h3><div class="map">${DATA.paths.map((p,i)=>`<div class="node"><div class="num">${i+1}</div><h4>${p.name}</h4><p>تقدم تجريبي لعرض لوحة الإحصائيات.</p><div class="progress"><i style="width:${45+i*10}%"></i></div></div>`).join('')}</div></div>`}
function resultsPage(){return `<div class="hero"><div><span class="eyebrow">تحليل التعلم</span><h1>النتيجة ليست رقمًا فقط.</h1><p>نظام النتائج يقسم الأداء إلى مهارات ومفاهيم تحتاج إلى مراجعة، ثم يعيدك للمادة المناسبة.</p></div><div class="result-ring"></div></div><div class="grid" style="margin-top:20px"><div class="card"><h4>نقطة قوة</h4><p>فهم المفاهيم الأساسية</p></div><div class="card"><h4>تحتاج مراجعة</h4><p>التطبيق على المسائل</p></div><div class="card"><h4>الخطوة التالية</h4><p>نشاط تفاعلي ثم اختبار قصير</p></div></div>`}
function guidePage(){return `<div class="hero"><div><span class="eyebrow">ابدأ هنا</span><h1>كيف تستخدم الموسوعة؟</h1><p>اختر المسار، افتح المادة، راجع المصدر الرسمي، ثم انتقل إلى النشاط التفاعلي والاختبار.</p></div></div><div class="map" style="margin-top:20px">${[['01','اختيار المسار','حدد المجال الذي تدرسه.'],['02','فتح الكتاب','انتقل مباشرة إلى المصدر الرسمي.'],['03','التفاعل','نفّذ نشاطًا أو تحديًا قصيرًا.'],['04','الاختبار','اختبر فهمك وحلل أخطاءك.']].map(x=>`<div class="node"><div class="num">${x[0]}</div><h4>${x[1]}</h4><p>${x[2]}</p></div>`).join('')}</div>`}
function settingsPage(){return `<div class="card"><h3>إعدادات الحساب والإدارة</h3><div class="form-grid"><label>اسم المستخدم<input id="setUser" value="${state.admin.username}"></label><label>البريد<input id="setEmail" value="${state.admin.email}"></label><label>اسم العرض<input id="setName" value="${state.admin.name}"></label><label>كلمة مرور جديدة<input id="setPass" type="password" placeholder="اتركها كما هي دون تغيير"></label></div><div class="modal-actions"><button class="primary" data-action="saveSettings">حفظ التغييرات</button></div></div>`}
function bindContent(){
 $$('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
 $$('[data-path]').forEach(b=>b.onclick=()=>{selectedPath=DATA.paths.find(p=>p.id===b.dataset.path);showPath(selectedPath)});
 $$('[data-subject]').forEach(b=>b.onclick=()=>showSubject(b.dataset.subject));
 $$('[data-url]').forEach(b=>b.onclick=()=>window.open(b.dataset.url,'_blank','noopener'));
 $$('[data-action="path"]').forEach(b=>b.onclick=()=>{page='paths';render()});$$('[data-action="library"]').forEach(b=>b.onclick=()=>{page='library';render()});
 $$('[data-action="addStudent"]').forEach(b=>b.onclick=studentModal);$$('[data-student]').forEach(b=>b.onclick=()=>studentModal(state.students.find(s=>s.id===b.dataset.student)));
 $$('[data-test]').forEach(b=>b.onclick=()=>startTest(+b.dataset.test));$$('[data-action="newTest"]').forEach(b=>b.onclick=()=>toast('تم فتح مساحة إنشاء الاختبار — اربط الأسئلة من بنك المحتوى.'));
 $('[data-action="saveSettings"]')?.addEventListener('click',()=>{state.admin.username=$('#setUser').value;state.admin.email=$('#setEmail').value;state.admin.name=$('#setName').value;if($('#setPass').value)state.admin.password=$('#setPass').value;save();currentUser=state.admin;toast('تم حفظ الإعدادات');render()});
 $('#subjectSearch')?.addEventListener('input',filterSubjects);$('#pathFilter')?.addEventListener('change',filterSubjects);
}
function filterSubjects(){const q=$('#subjectSearch').value.trim();const path=$('#pathFilter').value;let names=Object.keys(DATA.books);if(path!=='all')names=DATA.paths.find(p=>p.id===path).subjects;names=names.filter(x=>x.includes(q));$('#subjectGrid').innerHTML=names.map(subjectCard).join('');$$('[data-subject]').forEach(b=>b.onclick=()=>showSubject(b.dataset.subject))}
function showPath(p){selectedPath=p;openModal(`<h2>${p.name}</h2><p style="color:#697386">خريطة المواد التخصصية</p><div class="grid">${p.subjects.map(s=>`<button class="card" data-modal-subject="${esc(s)}"><h3>${s}</h3><p>${(DATA.demoLessons[s]||[]).length} مراحل تعليمية + كتاب رسمي + تقييمات</p></button>`).join('')}</div>`);$$('[data-modal-subject]').forEach(b=>b.onclick=()=>{closeModal();showSubject(b.dataset.modalSubject)})}
function showSubject(s){selectedSubject=s;const b=DATA.books[s]||{};const lessons=DATA.demoLessons[s]||[];openModal(`<div class="interactive"><div class="interactive-head"><div><span class="eyebrow">رحلة المادة</span><h2>${s}</h2><p>ابدأ من الكتاب الرسمي ثم انتقل إلى الخريطة التفاعلية.</p></div><div class="path-icon">◈</div></div><div class="lab-grid"><div class="lab"><h3>خريطة التعلم</h3>${lessons.map((l,i)=>`<div class="journey-step"><div class="journey-dot">${i+1}</div><div><h4>${l}</h4><small>محتوى + نشاط + سؤال</small></div></div>`).join('')}</div><div class="lab"><h3>المصادر</h3><p>الكتاب الرسمي:</p><button class="light-btn" data-url="${b.url||OFFICIAL}">فتح الجزء الأول ↗</button>${b.p2?`<button class="outline-light" style="margin-right:7px" data-url="${b.p2}">الجزء الثاني ↗</button>`:''}${b.assessment?`<p style="margin-top:22px">كتاب التقييمات:</p><button class="light-btn" data-url="${b.assessment}">فتح التقييمات ↗</button>`:''}<hr style="border-color:#ffffff16;margin:20px 0"><button class="light-btn" data-action="interactive">ابدأ النشاط التفاعلي</button></div></div></div>`);$$('[data-url]').forEach(x=>x.onclick=()=>window.open(x.dataset.url,'_blank','noopener'));$$('[data-action="interactive"]').forEach(x=>x.onclick=()=>showInteractive(s))}
function showInteractive(s){openModal(`<div class="interactive"><span class="eyebrow">مختبر تفاعلي</span><h2>${s}</h2><p>مثال قابل للتطوير داخل المحتوى: غيّر المتغير وشاهد أثره مباشرة.</p><div class="lab-grid"><div class="lab"><label>المتغير <b id="rangeVal">50</b></label><input id="labRange" class="range" type="range" min="10" max="90" value="50"><p>يمكن للإدارة لاحقًا ربط هذا المختبر بمفهوم محدد من الكتاب الرسمي.</p></div><div class="lab-output"><div id="ball" class="ball"></div></div></div><div class="modal-actions"><button class="light-btn" id="finishActivity">أنهي النشاط +10 نقاط</button></div></div>`);$('#labRange').oninput=e=>{$('#rangeVal').textContent=e.target.value;$('#ball').style.transform=`translateX(${(e.target.value-50)*2}px) translateY(${(50-e.target.value)*1.2}px)`};$('#finishActivity').onclick=()=>{const p=state.progress[currentUser.username]||{completed:0,percent:0};p.completed++;p.percent=Math.min(100,p.percent+5);state.progress[currentUser.username]=p;save();closeModal();toast('تم تسجيل النشاط +10 نقاط');render()}}
function startTest(type){let q=['أي خطوة تأتي بعد دراسة المصدر؟','ما الذي يضيفه النشاط التفاعلي؟','ما أفضل استخدام للنتيجة؟'];openModal(`<h2>اختبار قصير</h2><p style="color:#697386">3 أسئلة تجريبية لواجهة محرك الاختبارات.</p>${q.map((x,i)=>`<div class="question"><h4>${i+1}. ${x}</h4><div class="options">${['فهم وتطبيق','تجاهل المحتوى','الحفظ فقط'].map((o,j)=>`<button class="option" data-opt="${i}-${j}">${o}</button>`).join('')}</div></div>`).join('')}<div class="modal-actions"><button class="primary" id="submitTest">إنهاء الاختبار</button></div>`);$$('[data-opt]').forEach(o=>o.onclick=()=>{const parent=o.parentElement;parent.querySelectorAll('.option').forEach(x=>x.classList.remove('selected'));o.classList.add('selected')});$('#submitTest').onclick=()=>{closeModal();page='results';toast('تم تحليل الاختبار');render()}}
function studentModal(s={id:'',name:'',username:'',email:'',password:'Student@123',path:'eng'}){openModal(`<h2>${s.id?'تعديل طالب':'إضافة طالب'}</h2><div class="form-grid"><label>الاسم<input id="mName" value="${esc(s.name)}"></label><label>اسم المستخدم<input id="mUser" value="${esc(s.username)}"></label><label>البريد<input id="mEmail" value="${esc(s.email)}"></label><label>كلمة المرور<input id="mPass" value="${esc(s.password)}"></label><label class="full">المسار<select id="mPath">${DATA.paths.map(p=>`<option value="${p.id}" ${p.id===s.path?'selected':''}>${p.name}</option>`).join('')}</select></label></div><div class="modal-actions"><button class="primary" id="saveStudent">حفظ</button></div>`);$('#saveStudent').onclick=()=>{const obj={id:s.id||'s'+Date.now(),name:$('#mName').value,username:$('#mUser').value,email:$('#mEmail').value,password:$('#mPass').value,path:$('#mPath').value};if(s.id)state.students=state.students.map(x=>x.id===s.id?obj:x);else state.students.push(obj);save();closeModal();toast('تم حفظ الطالب');render()}}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')};function closeModal(){$('#modal').classList.add('hidden')};function esc(x=''){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');toast('تم تبديل المظهر')};$('#sourceBtn').onclick=()=>window.open(OFFICIAL,'_blank','noopener');$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#logoutBtn').onclick=()=>{currentUser=null;$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden');$('#loginPassword').value='';toast('تم تسجيل الخروج')};$('#openGuide').onclick=e=>{e.preventDefault();openModal(`<h2>دليل الاستخدام</h2><p>اختر نوع الحساب، سجّل الدخول، ثم استخدم خريطة المسار للوصول للمادة والكتاب والنشاط والاختبار.</p>`)};
$$('.role-tab').forEach(b=>b.onclick=()=>{$$('.role-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');role=b.dataset.role});
$('#loginForm').onsubmit=e=>{e.preventDefault();const u=$('#loginUsername').value.trim(),p=$('#loginPassword').value;if(role==='admin'){if((u===state.admin.username||u===state.admin.email)&&p===state.admin.password){currentUser=state.admin;enter()}else{$('#loginMessage').textContent='بيانات الإدارة غير صحيحة.'}}else{const s=state.students.find(x=>(x.username===u||x.email===u)&&x.password===p);if(s){currentUser=s;enter()}else $('#loginMessage').textContent='بيانات الطالب غير صحيحة.'}};
function enter(){sessionStorage.removeItem('MBC_SESSION');$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden');page='home';render()}
// Always require login on page load; no automatic old-session entry.
window.addEventListener('load',()=>{sessionStorage.removeItem('MBC_SESSION');$('#app').classList.add('hidden');$('#loginScreen').classList.remove('hidden')});
